apiVersion: v1
kind: Pod
metadata:
  namespace: leehorim
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
