apiVersion: v1
kind: Pod
metadata:
  name: nodesel-pod-a
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: pod-a-containers
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
---
apiVersion: v1
kind: Pod
metadata:
  name: nodesel-pod-b
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: pod-b-containers
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
# 또는
# nodeName:
#    k8s-node2
