apiVersion: v1
kind: Pod
metadata:
  name: cm-pod1
spec:
  containers:
  - image: nginx:1.21
    name: cm-container
    envFrom: # 어디로부터 환경변수를 가져올 것이다.
    - configMapRef: # configmap으로부터 가져올 것이다.
        name: log-level-cm
    
