apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:       # service에 붙이기 위한 label
    app: webapp
spec:
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: nginx-conf
  containers:
  - image: nginx:1.21-alpine
    name: nginx-proxy-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf  # 파일로 volume mount
      subPath: nginx.conf    # 파일 기반의 volume 설정에는 subpath가 필요하다
  - image: dbgurum/pyfla:1.0
    name: flask-container # config 파일에서 127.0.0.1:5000 으로 설정해주었기 때문에 굳이 포트설정 명시 x
