apiVersion: v1
kind: Pod
metadata:
  name: cip-pod
  labels:
    app: cipapp
spec:
  containers:
  - image: dbgurum/k8s-lab:v1.0
    name: cip-containers
    ports:
    - containerPort: 8080    

---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  selector:
    app: cipapp
  ports:
  - port: 9000
    targetPort: 8080