apiVersion: v1
kind: Service
metadata: 
  name: mynode2-svc
spec:
  selector:
    app: mynode
  ports:
  - port: 9000  #외부(url 접속할 때 이 포트사용)
    targetPort: 8000    #내부
    protocol: TCP
  externalIPs:
  - 192.168.56.101
