apiVersion: v1
kind: Pod
metadata:
  name: label-p1
  labels:
    type: infra
    job: web
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: p1-containers
---
apiVersion: v1
kind: Pod
metadata:
  name: label-p2
  labels:
    type: dev
    job: web
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: p2-containers
---
apiVersion: v1
kind: Pod
metadata:
  name: label-p3
  labels:
    type: infra
    job: db
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: p3-containers
---
apiVersion: v1
kind: Pod
metadata:
  name: label-p4
  labels:
    type: dev
    job: db
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: p4-containers
---
apiVersion: v1
kind: Pod
metadata:
  name: label-p5
  labels:
    type: infra
    job: web
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: p5-containers
---
apiVersion: v1
kind: Pod
metadata:
  name: label-p6
  labels:
    type: infra
    job: db
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: p6-containers
---
apiVersion: v1
kind: Service
metadata:
  name: infra-svc
spec:
  selector:
    type: infra
  ports:
  - port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: front-web-svc
spec:
  selector:
    job: web
  ports:
  - port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: infra-front-web-svc
spec:
  selector:
    type: dev
    job: web
  ports:
  - port: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector:
    job: db
  ports:
  - port: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: dev-db-svc
spec:
  selector:
    type: dev
    job: db
  ports:
  - port: 8085