apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp-pod
  template:
    metadata:
      labels:
        app: nodeapp-pod
    spec:
      containers:
      - image: dbgurum/k8s-lab:v1.0
        name: nodeapp-container
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-lb
spec:
  type: LoadBalancer
  selector:
    app: nodeapp-pod
  ports:
  - port: 80
    targetPort: 8080
