apiVersion: v1
kind: Pod
metadata:
  name: cm-sec-pod
spec:
  containers:
  - image: dbgurum/k8s-lab:initial
    name: cm-sec-container
    envFrom: 
    - configMapRef:
        name: cm-dev
    - secretRef: 
        name: sec-dev
    
