apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: leehorim
  name: dep-mainui
  annotations:
    kubernetes.io/change-cause: version 2.2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache
      app: main
      ref: stable
  template:
    metadata:
      labels:
        name: apache
        app: main
        ref: stable
    spec:
      containers:
      - image: http:2.2
        name: http2-contnr
