apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deploy
  namespace: my-ns1
  labels:
    run: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: my-app
  template:
    metadata:
      labels:
        run: my-app
    spec:
      containers:
      - image: nginx:1.21
        name: my-nginx-containers
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: my-svc
  namespace: my-ns1
spec:
  selector:
    run: my-app
  ports:
  - port: 8001
    targetPort: 80
    protocol: TCP