apiVersion: v1
kind: Pod
metadata:
  name: mynode-pod
spec:
  volumes:
  - name: mynode-path
    persistentVolumeClaim:        # pvc 선택
      claimName: pvc1
  containers:
  - image: dbgurum/mynode:2.0
    name: mynode-containers
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: mynode-path
      mountPath: /mynode