apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10G
  accessModes: 
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
spec:
  storageClassName: manual
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 3G
---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  volumes:
  - name: web-pv-storage
    persistentVolumeClaim:        
      claimName: pvc-volume
  containers:
  - image: nginx
    name: web-container
    ports:
    - containerPort: 80
      name: "web-server"
    volumeMounts:
    - name: web-pv-storage
      mountPath: "/usr/share/nginx/html"
