apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-2
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  volumes:
  - name: host-path
    hostPath:
      path: /data_dir
      type: DirectoryOrCreate # 없으면 만들어라. OS level이기 때문에 필요함
  containers:
  - image: dbgurum/k8s-lab:initial
    name: container1
    volumeMounts:
    - name: host-path
      mountPath: /mount
