apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-1
spec:
  # 전체 볼륨 정의
  volumes:
  - name: empty-dir
    emptyDir: {}
  containers:
  - image: dbgurum/k8s-lab:initial
    name: container1
    # 내부 볼륨 정의
    volumeMounts:
    - name: empty-dir
      mountPath: /mount1
  - image: dbgurum/k8s-lab:initial
    name: container2
    # 내부 볼륨 정의
    volumeMounts:
    - name: empty-dir
      mountPath: /mount2